### ISSUE TITLE
Task List - 07/22

### ISSUE THREAD

**Issue by SocAwk-Admin** [Adromero94/SocAwk#1]
3. [x] - Pick Blog page style - Kenny 
6. [x] - Remove Exclusive drops from home page - Dylans
4. [x] - What additional headers stay? - Kenny
10. [x] - Remove from "Sort By" drop down. (Ending Soon, Recently Sold, Less Viewed) - Dylan
11. [x] - Remove "Search NFT" from search bar - Dylan
12. [x] - Emotes on "Explore" Drop-down - Dylan
13. [x]  -  Change site title and image/logo on all  pages - Dylan
14. [x] - How it works > Get picture for front page - Kenny 
16. [x] - How it works> Remove "Explore" & "Create" button - Dylan
18. [x] - How it works> Create verbiage 
19. [x] -  Remove noise from Blog page - Dylan
20. [x] - Remove all unnecessary tabs from all pages and replace
21. [x] - Rename pages to match there role/title 
22. [x] - Create an About Us Page - Dylan
24. [x] - Remove map from Contact page - Dylan
25. [x] - Edit "Contact Us" contact information - Kenny/Dylan
8. [x] - Modify Footer - kenny/Dylan
27. [x]  - Add category emojis to all pages
32. [x] - Add Merch landing page
33. [x] - Remove Forgot password from Header list

7. [x] - Create social media accounts - Kenny
23. [x] - Create About Us Verbiage - Kenny
30. [x] -  Contact us Page > How it works Hyperlink. Change color/Make Bold
26. [x] - "About Us" page add social media to the 4 boxes
9. [ ] - Explore > All category > Select a Category. Redirect to corresponding group. - Dylan
17. [ ] - How it works> get icons & test for " Easy to get Started" - Kenny
28. [ ] - Profile page clean up
 31. [ ] - Create Cookie Policy Doc & Page - Dylan/Kenny
 34. [ ] - 
 35. [ ] 
---------------------------------------------------Database Issues-----------------------------------------------------
1. [ ] - Figure out database to use for JS - Kenny/Dylan 
2. [ ] - Account drop-down menu sign-in vs sign-out homepage - Dylan
3. [ ]  - If not signed in redirect checkout to create account -Dylan
4. [ ] - Profile, Signup and sign-in page update
5. [ ] -
6. [ ] -

**Comment by SocAwk-Admin** [comment]
>
